package com.romanmikhailenko.recipeapp.ui

const val ARG_CATEGORY_ID = "ARG_CATEGORY_ID"
const val ARG_CATEGORY_NAME = "ARG_CATEGORY_NAME"
const val ARG_CATEGORY_IMAGE_URL = "ARG_CATEGORY_IMAGE_URL"
const val ARG_RECIPE_ID = "ARG_RECIPE_ID"
const val ARG_RECIPE = "ARG_RECIPE"
const val PREFERENCE_FAVORITES = "PREFERENCE_FAVORITES"
const val PREFERENCE_FAVORITES_KEY = "PREFERENCE_FAVORITES_KEY"
